/// Dimensión de fechas (enero 2017 - agosto 2018).
table Calendario
	dataCategory: Time

	column Fecha
		dataType: dateTime
		isKey
		formatString: dd/mm/yyyy
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Año'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column 'Mes número'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: Mes número

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		summarizeBy: none
		sourceColumn: Mes
		sortByColumn: 'Mes número'

		annotation SummarizationSetBy = Automatic

	column 'Año-Mes número'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: Año-Mes número

		annotation SummarizationSetBy = Automatic

	column 'Mes y año'
		dataType: string
		summarizeBy: none
		sourceColumn: Mes y año
		sortByColumn: 'Año-Mes número'

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Número día semana'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: Número día semana

		annotation SummarizationSetBy = Automatic

	column 'Día de la semana'
		dataType: string
		summarizeBy: none
		sourceColumn: Día de la semana
		sortByColumn: 'Número día semana'

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
				    // Calendario continuo para el periodo analizado (enero 2017 - agosto 2018)
				    FechaInicio = #date(2017, 1, 1),
				    FechaFin = #date(2018, 8, 31),
				    ListaFechas = List.Dates(FechaInicio, Duration.Days(FechaFin - FechaInicio) + 1, #duration(1, 0, 0, 0)),
				    #"Convertido en tabla" = Table.FromList(ListaFechas, Splitter.SplitByNothing(), {"Fecha"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Convertido en tabla", {{"Fecha", type date}}),
				    #"Agregado año" = Table.AddColumn(#"Tipo cambiado", "Año", each Date.Year([Fecha]), Int64.Type),
				    #"Agregado mes número" = Table.AddColumn(#"Agregado año", "Mes número", each Date.Month([Fecha]), Int64.Type),
				    #"Agregado mes" = Table.AddColumn(#"Agregado mes número", "Mes", each Text.Proper(Date.MonthName([Fecha], "es-ES")), type text),
				    #"Agregado año-mes número" = Table.AddColumn(#"Agregado mes", "Año-Mes número", each [Año] * 100 + [Mes número], Int64.Type),
				    #"Agregado mes y año" = Table.AddColumn(#"Agregado año-mes número", "Mes y año", each Text.Start([Mes], 3) & " " & Text.From([Año]), type text),
				    #"Agregado trimestre" = Table.AddColumn(#"Agregado mes y año", "Trimestre", each "T" & Text.From(Date.QuarterOfYear([Fecha])), type text),
				    #"Agregado número día semana" = Table.AddColumn(#"Agregado trimestre", "Número día semana", each Date.DayOfWeek([Fecha], Day.Monday) + 1, Int64.Type),
				    #"Agregado día de la semana" = Table.AddColumn(#"Agregado número día semana", "Día de la semana", each Text.Proper(Date.DayOfWeekName([Fecha], "es-ES")), type text)
				in
				    #"Agregado día de la semana"

	annotation PBI_ResultType = Table
